server:
  port: 5250
spring:
  application:
    name: RecordService
  cloud:
    nacos:
      server-addr: localhost:8848
  config:
    import:
      - nacos:RecordService.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/unmanned_gym
    username: root
    password: 4114
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto  # 手动确认
        concurrency: 3
        max-concurrency: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#face:
#  port: 5000
#  python:
#    script-path: D:\IdeaProjects\AttendanceSystem\python\FaceService.py
#    service-url: http://localhost:5000
#  camera:
#    enabled: true
#    device-id: 0
#
#aliyun:
#  oss:
#    endpoint:   YOUR_OSS_ENDPOINT
#    bucket:     YOUR_OSS_BUCKET_NAME
#    access-key: YOUR_ALIYUN_ACCESS_KEY_ID
#    secret-key: YOUR_ALIYUN_ACCESS_KEY_SECRET
#    dir-prefix: user_face/       # 头像统一目录
#    illegal_dir-prefix: illegal_user_face/
#    local-base: D:\IdeaProjects\AttendanceSystem\data\face_cache